run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - noctx
    - unconvert
    - unparam
    - gocritic
    - gosec
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gosec:
    excludes:
      - G104  # Errors unhandled (handled by errcheck)
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0
